
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

	[types.cake]

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

	[types.leaves_type]

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.architects_palette]
			boards = true
			board_stairs = true
			railing = true
			board_wall = true
			board_slab = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.woodworks]
			bookshelf = true
			chiseled_bookshelf = true
			trapped_chest = true
			boards = true
			chest = true
			ladder = true
			beehive = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

